name: Deploy History Viewer

on:
  push:
    branches: ["production", "develop"]
  workflow_dispatch:

permissions:
  contents: write # Requis pour que l'action puisse écrire sur la branche github-pages

concurrency:
  # On ne veut pas que la prod et le dev déploient EXACTEMENT en même temps
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Déploiement si on est sur la branche PRODUCTION
      - name: Deploy Production
        if: github.ref_name == 'production'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./history-viewer # Le dossier contenant votre build
          branch: github-pages        # La branche cible pour GitHub Pages
          target-folder: .        # Déployé à la racine !

      # Déploiement si on est sur la branche DEVELOP
      - name: Deploy Develop
        if: github.ref_name == 'develop'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./history-viewer # Le dossier contenant votre build
          branch: github-pages        # Même branche cible
          target-folder: develop  # Déployé dans le sous-dossier /develop !